### ISSUE TITLE
Add Dominant Cycle Periods to HT Trendline

### ISSUE THREAD

**Issue by LeeDongGeon1996** [DaveSkender/Stock.Indicators.Python#340] opened 2024-01-17 13:43 UTC
- https://github.com/DaveSkender/Stock.Indicators/pull/948 (v2.4.1)

**Comment by LeeDongGeon1996** [comment] 2024-01-17 13:45
@DaveSkender  Can you force-remove this issue?

**Comment by DaveSkender** [comment] 2024-01-17 16:30
Duplicate of #338

**Comment by DaveSkender** [comment] 2024-01-17 16:31
I can fully delete too if desired, but just marked it as closed/duplicate initially.

**Closed by DaveSkender** 2024-01-17 16:30 UTC
Labels: duplicate
